---

- name: Install buisness apps from Deb
  apt:
    deb: "{{item}}"
    update_cache: yes
  loop:
    - https://go.skype.com/skypeforlinux-64.deb  
    

- apt_repository: Add nesessarry Repos
      repo: ppa:remmina-ppa-team/remmina-next
      state: present
     

- name: Install Remmina
  apt:
    pkg:
     - remmina
     - remmina-plugin-rdp 
     - remmina-plugin-secret
    update_cache: yes 

#- name: Install Prerequisites for Cisco
#  apt:
#    pkg:
#    - lib32z1

- name: Download Cisco
  get_url:
    url: http://dl1.technet24.ir/Downloads/Software/Cisco/AnyConnect/anyconnect-linux64-4.8.03052-predeploy-k9.tar.gz
    dest: /home/yasuro/Downloads/

- name: Unarchive Cisco  
  unarchive:
    src: /home/yasuro/Downloads/anyconnect-linux64-4.8.03052-predeploy-k9.tar.gz
    dest: /home/yasuro/Downloads/

- name: install Cisco
  shell: 
    chdir: /home/yasuro/Downloads/anyconnect-linux64-4.8.03052/vpn/
    cmd: yes | ./vpn_install.sh

